
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
     
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA3qcRjbeAGSKjV4xXEm6m92OKt360XsVE",
  authDomain: "parking-admin-93a60.firebaseapp.com",
  projectId: "parking-admin-93a60",
  storageBucket: "parking-admin-93a60.firebasestorage.app",
  messagingSenderId: "624678203760",
  appId: "1:624678203760:web:1ae05e22b33bfe5864dfb5",
  measurementId: "G-VBZGXTZN5S"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRRzp-TjsSj45NzpL2c-bHufTUsqxlyq8',
    appId: '1:624678203760:android:6d17990c0117dd4964dfb5',
    messagingSenderId: '624678203760',
    projectId: 'parking-admin-93a60',
    storageBucket: 'parking-admin-93a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVE9TPkeh6Z0-efMnA-V958fojTkxbzU',
    appId: '1:624678203760:ios:b9dd3e657b21fc0964dfb5',
    messagingSenderId: '624678203760',
    projectId: 'parking-admin-93a60',
    storageBucket: 'parking-admin-93a60.firebasestorage.app',
    iosBundleId: 'com.example.parkingAppAdmin',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyBawH_OWaQtgGoZlJXwpx6NBC3Ozt-crrQ',
  //   appId: '1:512603385853:ios:460f2ef78922ab7a44b394',
  //   messagingSenderId: '512603385853',
  //   projectId: 'foodisellerapp',
  //   storageBucket: 'foodisellerapp.appspot.com',
  //   iosBundleId: 'com.example.foodiiRidersApp.RunnerTests',
  // );
}